### ISSUE TITLE
Use atomic ref-counts

### ISSUE THREAD

**Issue by ericniebler** [toby-allsopp/ranges-coroutines#3]
I'm curious whether a smart-enough compiler is able to optimize/remove the atomic operations when it can determine there is no race. See http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0062r1.html and http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4455.html.

**Comment by toby-allsopp** [comment]
Yeah, I will get around to adding some bechmarks soon. Need to compare coroutine vs view_facade, ref-counted vs not, racy vs atomic, etc.

**Comment by toby-allsopp** [comment]
I've added some extremely simple benchmarking stuff and made the type of the reference count a template parameter. Using an `atomic<int>` is slightly slower with clang and pretty much the same with MSVC. The difference is dwarfed by the cost of creating the coroutine frame in the first place though - very disappinting how slow the coroutine version is.

**Comment by toby-allsopp** [comment]
I made a little tweak and now clang is able to completely optimze the coroutine away... as long as the ref count is not atomic :(

**Comment by ericniebler** [comment]
@CaseyCarter this is a strong argument against using atomics in a ranges-friendly `generator` that satisfies `View`. It may also be a strong argument to allow move-only views. Thoughts?

**Comment by CaseyCarter** [comment]
I think that move-only *single-pass* views make a lot of sense, as do move-only single-pass iterators. It would help to lock down the "calling begin only once" semantics for single pass views and "only the incremented iterator is valid" semantics for single pass iterators.

I would be less inclined to accept a suggestion that views should be exempt from res.on.races.

**Comment by ericniebler** [comment]
Generators are necessarily input. If we permitted move only input views, then IIUC we don't have to worry about res.on.races because there is only one not-moved-from value at a time. Right?

**Comment by ericniebler** [comment]
I'm being stupid, aren't I? A move-only generator wouldn't need reference counting at all. Duh.

**Comment by CaseyCarter** [comment]
Yes and yes. Much like with my hacky input ranges that mutate state in constant functions, there are no observable races in conforming programs.

**Comment by toby-allsopp** [comment]
Correct: if a move-only generator was allowe to be considered a View then we could dispense with all this reference counting malarky enitrely.

It's not really that useful to be able to copy a generator, or any single-pass range, as far as I can see, other than to make it easier to pass them around by value.

I also don't see why you'd ever want to get multiple threads involved when copying and destructing generators (it's not like you can make _n_ copies and read from them in _n_ threads), but I guess we have to assume users are idiots?

**Comment by ericniebler** [comment]
My personal preference is to leave `generator` copyable with non-atomic ref counts, and trust people to not be morons. Call it `thread_unsafe_generator`, or whatever.

**Comment by CaseyCarter** [comment]
> It's not really that useful to be able to copy a generator, or any single-pass range, as far as I can see, other than to make it easier to pass them around by value.

The same argument holds for single-pass iterators: they're copyable so we can pass them by value without using `std::move`, but the creation of copies has no useful effect. All we can really achieve by copying is to make uses of single-pass entities look like uses if multipass entities and thereby increase the chance of writing bugs.

> My personal preference is to leave `generator` copyable with non-atomic ref counts, and trust people to not be morons.

We'd need to hang flashing red signs on it indicating that copying or destroying copies of this particular model of `Copyable` in different threads can result in data races. This seems like a dangerous perversion of semantics to me.
